FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# omgprojects

## Projects Collection [/projects]

### List All Projects [GET]

+ Response 200 (application/json)

        [
            {
                "project_name": "Designing an online teaching tool",
                "published_at": "2016-04-05T08:40:51.620Z",
                "featured": false,
                "stats": [
                    {
                        "likes": 0,
                        "votes": 2048
                    },
                ]
            }
        ]

### Create a New Question [POST]

You may create your own question using this action. It takes a JSON
object containing a question and a collection of answers in the
form of choices.

+ Request (application/json)

        {
            "project_name": "Designing an online teaching tool",
            "stats": [
                "likes",
                "votes"
            ]
        }

+ Response 201 (application/json)

    + Headers

            Location: /projects/2

    + Body

            {
                "project_name": "Designing an online teaching tool",
                "published_at": "2016-04-05T08:40:51.620Z",
                "featured": false,
                "stats": [
                    {
                        "likes": 0,
                        "votes": 2048
                    },
                ]
            }